### ISSUE TITLE
s/ARC/something else

### ISSUE THREAD

**Issue by barnjamin** [algokittens/arc69#14]
If you're insistent about not having this in the foundations repo I think it should be renamed to something else to prevent confusion when ARC-0069 does come around

**Comment by ChrisAntaki** [comment]
<img width="694" alt="image" src="https://user-images.githubusercontent.com/1216762/146577647-94be5d3e-2abf-4c41-963a-ada5884e569d.png">

**Comment by barnjamin** [comment]
yep, forgot to close this
